In [1]:
import numpy as np

LAT = [12, 1, 20]
ELI = [5, 12, 9]

first_matrix_2d = np.array([[12, 1, 20], [5, 12, 9]])
print(first_matrix_2d.shape)
print(first_matrix_2d.ndim)

first_matrix = first_matrix_2d

print('first_matrix')
for row in first_matrix:
    print(row)

(2, 3)
2
first_matrix
[12  1 20]
[ 5 12  9]


In [3]:
2023-4-0o160 == [2, 0, 2]
2023-4-0o160 == [1, 6, 0]

second_matrix_2d = np.array([[2, 0, 2], [1, 6, 0]])
print(second_matrix_2d.shape)
print(second_matrix_2d.ndim)

second_matrix = second_matrix_2d

print('second_matrix')
for row in second_matrix:
    print(row)

(2, 3)
2
second_matrix
[2 0 2]
[1 6 0]


In [4]:
print(first_matrix)
print(second_matrix)

[[12  1 20]
 [ 5 12  9]]
[[2 0 2]
 [1 6 0]]


In [5]:
array_first_matrix = np.array(first_matrix)
array_second_matrix = np.array(second_matrix)

third_matrix = (array_first_matrix + array_second_matrix)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[14  1 22]
[ 6 18  9]


In [6]:
array_first_matrix = np.array(first_matrix)

fourth_matrix = (array_first_matrix * 2)

print('fourth_matrix')
for row in fourth_matrix:
    print(row)

fourth_matrix
[24  2 40]
[10 24 18]


In [7]:
second_matrix = np.array(second_matrix)
second_matrix_T = second_matrix.T

fifth_matrix = (second_matrix.T)

print('fifth_matrix')
for row in fifth_matrix:
    print(row)

fifth_matrix
[2 1]
[0 6]
[2 0]


In [8]:
third_matrix = np.array(second_matrix)
third_matrix_T = third_matrix.T

third_matrix = third_matrix.T

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[2 1]
[0 6]
[2 0]


In [10]:
array_third_matrix = np.array(third_matrix)
array_fifth_matrix = np.array(third_matrix)

sixth_matrix = (array_third_matrix * array_fifth_matrix)

print('sixth_matrix')
for row in sixth_matrix:
    print(row)

sixth_matrix
[4 1]
[ 0 36]
[4 0]


In [12]:
array_third_matrix = np.array(third_matrix)

sum_third_matrix = np.sum(third_matrix)

print(sum_third_matrix)

11


In [13]:
seventh_matrix = np.zeros ((2, 3))

print('seventh_matrix')
for row in seventh_matrix:
    print(row)

seventh_matrix
[0. 0. 0.]
[0. 0. 0.]
